name: Data Workflow

on:
  schedule:
    - cron: "23 19 * * *"
  workflow_dispatch:

jobs:
  data_workflow:
    runs-on: ubuntu-latest
    environment: "data-workflow"
    env:
      COCKROACH_CONNECTION_STRING: ${{ secrets.COCKROACH_CONNECTION_STRING }}
      DO_SHEETS_WORKFLOW: false
      DO_UPDATE_AO_INFO: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pipenv --user
          pipenv install --deploy
        working-directory: ./data-workflow
      - name: Run Workflow
        run: |
          pipenv run python main.py
        working-directory: ./data-workflow

  data_validation:
    needs: data_workflow
    runs-on: ubuntu-latest
    environment: "data-workflow"
    env:
      COCKROACH_CONNECTION_STRING: ${{ secrets.COCKROACH_CONNECTION_STRING }}
      GX_CLOUD_ACCESS_TOKEN: ${{ secrets.GX_CLOUD_ACCESS_TOKEN }}
      GX_CLOUD_ORGANIZATION_ID: ${{ vars.GX_CLOUD_ORGANIZATION_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pipenv --user
          pipenv install --deploy
        working-directory: ./data-validation
      - name: Run Workflow
        run: |
            pipenv run python main.py
        working-directory: ./data-validation
