name: Data Workflow

on:
  schedule:
    - cron: "23 19 * * *"
  workflow_dispatch:


jobs:
  data_workflow:
    runs-on: ubuntu-latest
    environment: "data-workflow"
    env:
      COCKROACH_CONNECTION_STRING: ${{ secrets.COCKROACH_CONNECTION_STRING }}
      DO_SHEETS_WORKFLOW: false
      DO_UPDATE_AO_INFO: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data-workflow/requirements.txt
      - name: Run Workflow
        run: |
          python data-workflow/main.py
  
  data_validation:
    needs: data_workflow
    runs-on: ubuntu-latest
    environment: "data-workflow"
    env:
      COCKROACH_CONNECTION_STRING: ${{ secrets.COCKROACH_CONNECTION_STRING }}
      GX_CLOUD_ACCESS_TOKEN: ${{ secrets.GX_CLOUD_ACCESS_TOKEN }}
      GX_CLOUD_ORGANIZATION_ID: ${{ vars.GX_CLOUD_ORGANIZATION_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data-validation/requirements.txt
      - name: Run Workflow
        run: |
          python data-validation/main.py
