on:
  push:
    branches:
    - develop

jobs:
  deploy:
    uses: jcampbell/f3_bot/.github/workflows/gcf.yml@develop
    with:
      environment: development
      slackbot_name: slackbot-develop
      queue_handler_name: f3-sheets-handler-develop
    secrets:
      GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
      GCP_PROJECT: '${{ secrets.GCP_PROJECT }}'
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'
