name: Deploy Green Level slackbot

on:
  push:
    branches:
    - main

jobs:
  deploy:
    uses: f3peakcity/f3_bot/.github/workflows/gcf.yml@main
    with:
      environment: peakcity
      slackbot_name: slackbot-greenlevel
      queue_handler_name: f3-sheets-handler-greenlevel
      env_vars_file: ./.github/workflows/env-greenlevel.yml
    secrets:
      GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
      GCP_PROJECT: '${{ secrets.GCP_PROJECT }}'
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'

