name: Deploy Development Environment

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    uses: f3peakcity/f3_bot/.github/workflows/gcf.yml@develop
    with:
      environment: development
      slackbot_name: slackbot-develop
      queue_handler_name: f3-sheets-handler-develop
      env_vars_file: ./env/env-development.yml
    secrets:
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'
