on:
  push:
    branches:
    - develop

jobs:
  deploy:
    uses: ./.github/workflows/gcf.yml@develop
    with:
      slackbot_name: slackbot-develop
      queue_handler_name: f3-sheets-handler-develop
