name: Deploy Peak City

on:
  push:
    branches:
    - main

jobs:
  deploy:
    uses: f3peakcity/f3_bot/.github/workflows/gcf.yml@main
    with:
      environment: peakcity
      slackbot_name: slackbot-peakcity
      queue_handler_name: f3-sheets-handler-peakcity
      env_vars_file: ./env/env-peakcity.yml
    secrets:
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'
