name: Deploy peakcity slackbot

on:
  push:
    branches:
    - peakcity

jobs:
  deploy:
    uses: jcampbell/f3_bot/.github/workflows/gcf.yml@peakcity
    with:
      environment: peakcity
      slackbot_name: slackbot-peakcity
      queue_handler_name: f3-sheets-handler-peakcity
    secrets:
      GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
      GCP_PROJECT: '${{ secrets.GCP_PROJECT }}'
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'

