name: Deploy greenlevel slackbot

on:
  push:
    branches:
    - greenlevel

jobs:
  deploy:
    uses: jcampbell/f3_bot/.github/workflows/gcf.yml@greenlevel
    with:
      environment: greenlevel
      slackbot_name: slackbot-greenlevel
      queue_handler_name: f3-sheets-handler-greenlevel
    secrets:
      GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
      GCP_PROJECT: '${{ secrets.GCP_PROJECT }}'
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'

