name: Deploy Green Level

on:
  push:
    branches:
    - main

jobs:
  deploy:
    uses: f3peakcity/f3_bot/.github/workflows/gcf.yml@main
    with:
      environment: greenlevel
      slackbot_name: slackbot-greenlevel
      queue_handler_name: f3-sheets-handler-greenlevel
      env_vars_file: ./env/env-greenlevel.yml
    secrets:
      SLACKBOT_ENV_VARS: '${{ secrets.SLACKBOT_ENV_VARS }}'
