name: Deploy slackbot to GCP

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      queue_handler_name:
        required: true
        type: string
      slackbot_name:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT:
        required: true
      SLACKBOT_ENV_VARS:
        required: true

jobs:
  deploy-queue-handler:
    name: Deploy Queue Handler
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Queue Handler
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ inputs.queue_handler_name }}
        entry_point: f3_sheets_handler
        runtime: python39
        region: us-east1
        source_dir: ./sheets_task/
        env_vars: ${{ secrets.SLACKBOT_ENV_VARS }}

  deploy-slackbot:
    name: Deploy Slackbot
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Slackbot
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ inputs.slackbot_name }}
        runtime: python39
        region: us-east1
        source_dir: ./slackbot/
        env_vars: ${{ secrets.SLACKBOT_ENV_VARS }}
