name: Deploy slackbot to GCP

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      queue_handler_name:
        required: true
        type: string
      slackbot_name:
        required: true
        type: string
      env_vars_file:
        required: true
        type: string
    secrets:
      # GCP_SA_KEY:
      #   required: true
      GCP_PROJECT:
        required: true
      SLACKBOT_ENV_VARS:
        required: true

jobs:
  deploy-queue-handler:
    name: Deploy Queue Handler
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/330812298791/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'github-action-runner@f3-carpex.iam.gserviceaccount.com'
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v0'
    #   with:
    #     credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Queue Handler
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ inputs.queue_handler_name }}
        entry_point: f3_sheets_handler
        runtime: python39
        region: us-east1
        source_dir: ./sheets_task/src
        env_vars: ${{ secrets.SLACKBOT_ENV_VARS }}
        env_vars_file: ${{ inputs.env_vars_file }}

  deploy-slackbot:
    name: Deploy Slackbot
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Slackbot
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: ${{ inputs.slackbot_name }}
        entry_point: slackbot
        runtime: python39
        region: us-east1
        source_dir: ./slackbot/
        env_vars: ${{ secrets.SLACKBOT_ENV_VARS }}
        env_vars_file: ${{ inputs.env_vars_file }}
