name: Slackbot Warmup

on:
  # Every 7 minutes during peak workout hours
  # Runtime is UTC, so adapt to Eastern Time
  schedule:
    - cron: "*/7 10,11 * * *"
  workflow_dispatch:

jobs:
  warmup_slackbot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Warmup Slackbot
        run: |
          curl -q https://us-east1-f3-carpex.cloudfunctions.net/slackbot/healthz
          curl -q https://us-east1-f3-carpex.cloudfunctions.net/slackbot-peakcity/healthz
          curl -q https://us-east1-f3-carpex.cloudfunctions.net/slackbot-greenlevel/healthz
          curl -q https://us-east1-f3-carpex.cloudfunctions.net/slackbot-churham/healthz
